import type { EditorStylePreset } from "./types";

export const STYLE_PRESETS: EditorStylePreset[] = [
  {
    id: "corporate",
    name: "Corporate",
    description: "Professionnel et épuré, idéal pour le B2B",
    primaryColor: "#1a2744",
    secondaryColor: "#ffffff",
    accentColor: "#3d9b8f",
    fontFamily: "Inter, sans-serif",
    titleStyle: {
      fontSize: 32,
      fontWeight: "700",
      color: "#ffffff",
      backgroundColor: "rgba(26, 39, 68, 0.85)",
      padding: 16,
      borderRadius: 8,
      textAlign: "left",
      animation: "fadeIn",
    },
    subtitleStyle: {
      fontSize: 18,
      fontWeight: "400",
      color: "#e0e0e0",
      backgroundColor: "rgba(26, 39, 68, 0.7)",
      padding: 12,
      borderRadius: 6,
      textAlign: "left",
      animation: "fadeIn",
    },
    businessCardStyle: "corporate",
  },
  {
    id: "modern",
    name: "Moderne",
    description: "Design audacieux avec des couleurs vives",
    primaryColor: "#6366f1",
    secondaryColor: "#f8fafc",
    accentColor: "#f59e0b",
    fontFamily: "Inter, sans-serif",
    titleStyle: {
      fontSize: 36,
      fontWeight: "800",
      color: "#ffffff",
      backgroundColor: "rgba(99, 102, 241, 0.9)",
      padding: 20,
      borderRadius: 12,
      textAlign: "center",
      animation: "slideUp",
      letterSpacing: -0.5,
    },
    subtitleStyle: {
      fontSize: 20,
      fontWeight: "500",
      color: "#ffffff",
      backgroundColor: "rgba(99, 102, 241, 0.7)",
      padding: 14,
      borderRadius: 10,
      textAlign: "center",
      animation: "slideUp",
    },
    businessCardStyle: "modern",
  },
  {
    id: "minimal",
    name: "Minimaliste",
    description: "Simple et élégant, l'essentiel uniquement",
    primaryColor: "#18181b",
    secondaryColor: "#fafafa",
    accentColor: "#71717a",
    fontFamily: "Inter, sans-serif",
    titleStyle: {
      fontSize: 28,
      fontWeight: "600",
      color: "#ffffff",
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      padding: 12,
      borderRadius: 4,
      textAlign: "left",
      animation: "fadeIn",
      letterSpacing: 0.5,
    },
    subtitleStyle: {
      fontSize: 16,
      fontWeight: "400",
      color: "#d4d4d8",
      padding: 8,
      borderRadius: 4,
      textAlign: "left",
      animation: "fadeIn",
    },
    businessCardStyle: "minimal",
  },
  {
    id: "bold",
    name: "Bold",
    description: "Impact maximum, accrocheur et dynamique",
    primaryColor: "#dc2626",
    secondaryColor: "#000000",
    accentColor: "#facc15",
    fontFamily: "Inter, sans-serif",
    titleStyle: {
      fontSize: 42,
      fontWeight: "900",
      color: "#ffffff",
      backgroundColor: "rgba(220, 38, 38, 0.9)",
      padding: 20,
      borderRadius: 0,
      textAlign: "center",
      animation: "slideLeft",
      letterSpacing: -1,
      textShadow: "2px 2px 4px rgba(0,0,0,0.5)",
    },
    subtitleStyle: {
      fontSize: 22,
      fontWeight: "700",
      color: "#facc15",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      padding: 14,
      borderRadius: 0,
      textAlign: "center",
      animation: "slideLeft",
    },
    businessCardStyle: "bold",
  },
];
